name: 알라딘 관리자페이지 자동배포

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 6.14.1
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-    
            
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v2  
  
      - name: PnPm 으로 노드모듈 설치
        run: pnpm install
  
      - name: Build SvelteKit application
        run: pnpm run build
  
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          source: 'build/*'
          target: '/var/www/html'
